<?xml version="1.0" encoding="utf-8"?><Database Name="MiniPIM" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=MiniPIM;Integrated Security=True" SettingsObjectName="WindowsFormsApplication2.Properties.Settings" SettingsPropertyName="MiniPIMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Atributo" Member="Atributo">
    <Type Name="Atributo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_cuenta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Atributo_ValorAtributo" Member="ValorAtributo" ThisKey="id" OtherKey="atributo_id" Type="ValorAtributo" />
      <Association Name="Cuenta_Atributo" Member="Cuenta" ThisKey="nombre_cuenta" OtherKey="nombre" Type="Cuenta" IsForeignKey="true" />
      <Association Name="TipoAtributo_Atributo" Member="TipoAtributo" ThisKey="tipo" OtherKey="id" Type="TipoAtributo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ValorAtributo" Member="ValorAtributo">
    <Type Name="ValorAtributo">
      <Column Name="valor" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="atributo_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="producto_SKU" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Atributo_ValorAtributo" Member="Atributo" ThisKey="atributo_id" OtherKey="id" Type="Atributo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Producto_ValorAtributo" Member="Producto" ThisKey="producto_SKU" OtherKey="SKU" Type="Producto" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_cuenta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_ProductoCategoria" Member="ProductoCategoria" ThisKey="id" OtherKey="categoria_id" Type="ProductoCategoria" />
      <Association Name="Cuenta_Categoria" Member="Cuenta" ThisKey="nombre_cuenta" OtherKey="nombre" Type="Cuenta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cuenta" Member="Cuenta">
    <Type Name="Cuenta">
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fechaCreacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Cuenta_Atributo" Member="Atributo" ThisKey="nombre" OtherKey="nombre_cuenta" Type="Atributo" />
      <Association Name="Cuenta_Categoria" Member="Categoria" ThisKey="nombre" OtherKey="nombre_cuenta" Type="Categoria" />
      <Association Name="Cuenta_Producto" Member="Producto" ThisKey="nombre" OtherKey="nombre_cuenta" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="Thumbnail" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SKU" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="GTIN" Type="System.String" DbType="Char(14) NOT NULL" CanBeNull="false" />
      <Column Name="nombre_cuenta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Producto_ValorAtributo" Member="ValorAtributo" ThisKey="SKU" OtherKey="producto_SKU" Type="ValorAtributo" />
      <Association Name="Producto_ProductoCategoria" Member="ProductoCategoria" ThisKey="SKU" OtherKey="producto_SKU" Type="ProductoCategoria" />
      <Association Name="Producto_Relacion" Member="Relacion" ThisKey="SKU" OtherKey="producto_SKU1" Type="Relacion" />
      <Association Name="Producto_Relacion1" Member="Relacion1" ThisKey="SKU" OtherKey="producto_SKU2" Type="Relacion" />
      <Association Name="Cuenta_Producto" Member="Cuenta" ThisKey="nombre_cuenta" OtherKey="nombre" Type="Cuenta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductoCategoria" Member="ProductoCategoria">
    <Type Name="ProductoCategoria">
      <Column Name="producto_SKU" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="categoria_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Categoria_ProductoCategoria" Member="Categoria" ThisKey="categoria_id" OtherKey="id" Type="Categoria" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Producto_ProductoCategoria" Member="Producto" ThisKey="producto_SKU" OtherKey="SKU" Type="Producto" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Relacion" Member="Relacion">
    <Type Name="Relacion">
      <Column Name="nombre" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="producto_SKU1" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="producto_SKU2" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Producto_Relacion" Member="Producto" ThisKey="producto_SKU1" OtherKey="SKU" Type="Producto" IsForeignKey="true" />
      <Association Name="Producto_Relacion1" Member="Producto1" ThisKey="producto_SKU2" OtherKey="SKU" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoAtributo" Member="TipoAtributo">
    <Type Name="TipoAtributo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TipoAtributo_Atributo" Member="Atributo" ThisKey="id" OtherKey="tipo" Type="Atributo" />
    </Type>
  </Table>
</Database>